Changed yaml files

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -1,10 +1,6 @@
 name: Java CI with Maven
 
-on:
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+on: [push]
 
 jobs:
   build:
@@ -12,12 +8,52 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pandas
+          pip install numpy
+      - run: sudo apt update
+      - run: sudo apt install inotify-tools
+      - run: inotifywait -mr /home/runner/work/spring-petclinic-rest/spring-petclinic-rest/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
+      - run: touch starting_build_uses-checkout_15
+      - run: rm starting_build_uses-checkout_15
       - uses: actions/checkout@v2
+      - run: touch starting_build_SetupJDK11_16
+      - run: rm starting_build_SetupJDK11_16
       - name: Set up JDK 11
         uses: actions/setup-java@v2
         with:
           java-version: '11'
           distribution: 'adopt'
           cache: maven
+      - run: touch starting_build_BuildwithMaven_22
+      - run: rm starting_build_BuildwithMaven_22
       - name: Build with Maven
         run: mvn -B install --file pom.xml
+      - run: touch starting_finished_finished_8979874
+        if: always()
+      - run: rm starting_finished_finished_8979874
+        if: always()
+      - name: Execute py script # run file
+        if: always()
+        run: |
+          echo pwd
+          ls -la
+          python .github/workflows/script.py
+      - name: Check push directory exit code
+        if: always()
+        run: |
+          echo 'push failed, trying pull and then push'
+          git config --global user.name 'UT-SE-Research'
+          git config --global user.email 'ocibsummerresearch2022@gmail.com'
+          git add .
+          git commit -m 'rebased and pushed ${{ github.head_ref }}'
+          while ! git push origin 1676957968-c0ae930; do
+            git pull --rebase https://github.com/UT-SE-Research/ci-analyzes.git 1676957968-c0ae930
+            git remote set-url origin https://UT-SE-Research:${{ secrets.API_TOKEN_GITHUB }}@github.com/UT-SE-Research/ci-analyzes.git
+            git push -f origin 1676957968-c0ae930
+          done
